LifeManagement/Models/DB/UserSetting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using LifeManagement.Enums;
using LifeManagement.Resources;
using System.ComponentModel.DataAnnotations.Schema;

namespace LifeManagement.Models.DB
{
    public class UserSetting : IEntity
    {
            public Guid Id { get; set; }
            public string UserId { get; set; }
            public TimeSpan ComplexityLowFrom { get; set; }
            public TimeSpan ComplexityLowTo { get; set; }
            public TimeSpan ComplexityMediumTo { get; set; }
            public TimeSpan ComplexityHightTo { get; set; }

            [Display(Name = "ParallelismPercentage", ResourceType = typeof(ResourceScr))]
            public int ParallelismPercentage { get; set; }

            [Display(Name = "WorkingTime", ResourceType = typeof(ResourceScr))]    
            public TimeSpan WorkingTime { get; set; }

            public Int64 TimeZoneShiftTicks { get; set; }
        
            [NotMapped]
            [Display(Name = "TimeZone", ResourceType = typeof(ResourceScr))]
            public TimeSpan TimeZoneShift {
                get { return TimeSpan.FromTicks(TimeZoneShiftTicks); }
                set { TimeZoneShiftTicks = value.Ticks; }
            }
            public virtual ApplicationUser User { get; set; }

            public UserSetting()
            {
                Id = Guid.NewGuid();
                SetDefault();
            }

            public UserSetting(string userId) : this()
            {
                UserId = userId;
            }

        public void SetDefault()
        {
            ComplexityLowFrom = new TimeSpan(0, 15, 0);
            ComplexityLowTo = new TimeSpan(1, 20, 0);
            ComplexityMediumTo = new TimeSpan(3, 30, 0);
            ComplexityHightTo = new TimeSpan(10, 30, 0);
            ParallelismPercentage = 30;
            WorkingTime = new TimeSpan(16, 0, 0);
            TimeZoneShift = new TimeSpan(0, 2, 0);
        }

        public TimeSpan[] GetRange(Complexity complexity)
        {
            var result = new TimeSpan[2];
            switch (complexity)
            {
                case Complexity.Low:
                    result[0] = ComplexityLowFrom;
                    result[1] = ComplexityLowTo;
                    break;
                case Complexity.Medium:
                    result[0] = ComplexityLowTo.Add(new TimeSpan(0, 1, 0));
                    result[1] = ComplexityMediumTo;
                    break;
                case Complexity.Hight:
                    result[0] = ComplexityMediumTo.Add(new TimeSpan(0,1,0));
                    result[1] = ComplexityHightTo;
                    break;
                default:
                    result[0] = new TimeSpan(0, 15, 0);
                    result[1] = new TimeSpan(0,30,0);
                    break;
            }
            return result;
        }


        public TimeSpan GetMaxComplexityRange(Complexity complexity)
        {
            switch (complexity)
            {
                case Complexity.Low:
                    return ComplexityLowTo;
                case Complexity.Medium:
                    return ComplexityMediumTo;
                case Complexity.Hight:
                    return ComplexityHightTo;
                default:
                    return new TimeSpan(0, 30, 0);
            }
        }

        public TimeSpan GetAverageComplexityRange(Complexity complexity)
        {
            var result = GetRange(complexity);
            return result[0].Add(TimeSpan.FromMinutes(result[1].Subtract(result[0]).TotalMinutes/2));

        }
        public TimeSpan GetMinComplexityRange(Complexity complexity)
        {
            switch (complexity)
            {
                case Complexity.Low:
                    return ComplexityLowFrom;
                case Complexity.Medium:
                    return ComplexityLowTo;
                case Complexity.Hight:
                    return ComplexityMediumTo;
                default:
                    return new TimeSpan(0, 15, 0);
            }
        }

    }
}

LifeManagement/Controllers/UserSettingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LifeManagement.Attributes;
using LifeManagement.Models.DB;
using LifeManagement.Models;
using Microsoft.AspNet.Identity;

namespace LifeManagement.Controllers
{

    [Authorize]
    [Localize]
    public class UserSettingController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /UserSetting/Edit/5
        public async Task<ActionResult> Edit()
        {
            var userId = User.Identity.GetUserId();
            UserSetting usersetting = await db.UserSettings.FirstOrDefaultAsync(x => x.UserId == userId);
            if (usersetting == null)
            {
                usersetting = new UserSetting();
                usersetting.UserId = userId;
                db.UserSettings.Add(usersetting);
                await db.SaveChangesAsync();
            }
            return PartialView("Edit", usersetting);
        }


        // POST: /UserSetting/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,UserId,ComplexityLowFrom,ComplexityLowTo,ComplexityMediumTo,ComplexityHightTo,ParallelismPercentage,WorkingTime,TimeZoneShiftTicks")] UserSetting usersetting)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usersetting).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return Json(new { success = true });
            }
            return PartialView("Edit", usersetting);
        }

        private SelectList CreateTimeZoneList(TimeSpan timeShift)
        {
            List<KeyValuePair<TimeSpan, string>> timeList = new List<KeyValuePair<TimeSpan, string>>()
            {
                new KeyValuePair<TimeSpan, string>(new TimeSpan(-12, 0, 0), "UTC-12"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(-11, 0, 0), "UTC-11"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(-10, 0, 0), "UTC-10"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(-9, 0, 0), "UTC-9"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(-8, 0, 0), "UTC-8"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(-7, 0, 0), "UTC-7"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(-6, 0, 0), "UTC-6"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(-5, 0, 0), "UTC-5"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(-4, 30, 0), "UTC-4:30"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(-4, 0, 0), "UTC-4"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(-3, 30, 0), "UTC-3:30"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(-2, 0, 0), "UTC-2"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(-1, 0, 0), "UTC-1"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(0, 0, 0), "UTC+0"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(1, 0, 0), "UTC+1"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(2, 0, 0), "UTC+2"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(3, 0, 0), "UTC+3"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(3, 30, 0), "UTC+3:30"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(4, 0, 0), "UTC+4"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(4, 30, 0), "UTC+4:30"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(5, 0, 0), "UTC+5"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(5, 30, 0), "UTC+5:30"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(5, 45, 0), "UTC+5:45"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(6, 0, 0), "UTC+6"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(6, 30, 0), "UTC+6:30"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(7, 0, 0), "UTC+7"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(8, 0, 0), "UTC+8"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(8, 45, 0), "UTC+8:45"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(9, 0, 0), "UTC+9"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(9, 30, 0), "UTC+9:30"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(10, 0, 0), "UTC+10"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(10, 30, 0), "UTC+10:30"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(11, 0, 0), "UTC+11"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(11, 30, 0), "UTC+11:30"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(12, 0, 0), "UTC+12"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(12, 45, 0), "UTC+12:45"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(13, 0, 0), "UTC+13"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(13, 45, 0), "UTC+13:45"),
                new KeyValuePair<TimeSpan, string>(new TimeSpan(14, 0, 0), "UTC+14")
            };
            return new SelectList(timeList, "Key", "Value", timeShift);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public async Task<ActionResult> ToDefault([Bind(Include = "Id,UserId,ComplexityLowFrom,ComplexityLowTo,ComplexityMediumTo,ComplexityHightTo,ParallelismPercentage,WorkingTime")] UserSetting settings)
        {
            if (settings == null)
            {
                return HttpNotFound();
            }
            settings.SetDefault();
            if (ModelState.IsValid)
            {
                db.Entry(settings).State = EntityState.Modified;
                await db.SaveChangesAsync();
            }
            return Json(new { success = true });
        }
    }
}

LifeManagement/Views/UserSetting/Edit.cshtml
@using System.Web.Mvc.Html5
@using LifeManagement.Extensions
@using LifeManagement.Resources
@model LifeManagement.Models.DB.UserSetting




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontalLM">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.TimeZoneShiftTicks)

        <div class="form-group">
            @Html.LabelFor(model => model.WorkingTime, new { @class = "control-label LMсol-md-3" })
            <div class="LMсol-md-9 formaReadOnly">
                @Html.Html5EditorFor(model => model.WorkingTime, InputTypes.InputType.Text, htmlAttributes: new
                {
                    @required = "true",
                    @class = " short",
                    @readonly = "readonly",
                    @value = @Model.WorkingTime.Hours + ":" + @Model.WorkingTime.Minutes
                })
                <input type="text" id="Hours" value="@Model.WorkingTime.Hours" disabled />
                @LifeManagement.Resources.ResourceScr.hours
                <input type="text" id="Minutes" value="@Model.WorkingTime.Minutes" disabled />
                @LifeManagement.Resources.ResourceScr.minutes
                <br />
                <div class="sliderLong" id="sliderWorking" data-start-value="@Model.WorkingTime.TotalMinutes"></div>
                <br />
                @Html.ValidationMessageFor(model => model.WorkingTime)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ParallelismPercentage, new {@class = "control-label LMсol-md-3"})
            <div class="LMсol-md-9 formaReadOnly">
                @Html.Html5EditorFor(model => model.ParallelismPercentage, InputTypes.InputType.Text, htmlAttributes: new {@required = "true", @class = "Percentage short", @readonly = "readonly"})%
                <br/>
                <div class="sliderPercentage sliderLong" data-start-value="@Model.ParallelismPercentage"></div>
                <br/>
                @Html.ValidationMessageFor(model => model.ParallelismPercentage)
            </div>
        </div>

        <strong>@ResourceScr.ComplexitySettings :</strong>
        <div class="form-group">
            @Html.Label(ResourceScr.Low, new { @class = "control-label LMсol-md-3" })
            <div class="LMсol-md-9 formaReadOnly" id="Low">
                @Html.Html5EditorFor(model => model.ComplexityLowFrom, InputTypes.InputType.Text, htmlAttributes: new { @required = "true", @class = "short", @readonly = "readonly" }) -
                @Html.Html5EditorFor(model => model.ComplexityLowTo, InputTypes.InputType.Text, htmlAttributes: new { @required = "true", @class = " short", @readonly = "readonly" })
                <div class="sliderLong" id="slider-rangeLow" data-start-value-from="@Model.ComplexityLowFrom.TotalMinutes" data-start-value-to="@Model.ComplexityLowTo.TotalMinutes"></div>
                @Html.ValidationMessageFor(model => model.ComplexityLowFrom)
            </div>
        </div>

        <div class="form-group" >
            @Html.Label(ResourceScr.Medium, new { @class = "control-label LMсol-md-3" })
            <div class="LMсol-md-9 formaReadOnly" id="Medium">
                @Html.Html5EditorFor(model => model.ComplexityLowTo, InputTypes.InputType.Text, htmlAttributes: new { @required = "true", @class = " short", @readonly = "readonly" }) -
                @Html.Html5EditorFor(model => model.ComplexityMediumTo, InputTypes.InputType.Text, htmlAttributes: new { @required = "true", @class = " short", @readonly = "readonly" })
                <div class="sliderLong" id="slider-rangeMedium" data-start-value-from="@(Model.ComplexityLowTo.TotalMinutes+1)" data-start-value-to="@Model.ComplexityMediumTo.TotalMinutes"></div>
                @Html.ValidationMessageFor(model => model.ComplexityMediumTo)
            </div>
        </div>

        <div class="form-group">
            @Html.Label(ResourceScr.High, new {@class = "control-label LMсol-md-3"})
            <div class="LMсol-md-9 formaReadOnly" id="Hight">
                @Html.Html5EditorFor(model => model.ComplexityMediumTo, InputTypes.InputType.Text, htmlAttributes: new { @required = "true", @class = " short", @readonly = "readonly" }) -
                @Html.Html5EditorFor(model => model.ComplexityHightTo, InputTypes.InputType.Text, htmlAttributes: new { @required = "true", @class = " short", @readonly = "readonly" })
                <div class="sliderLong" id="slider-rangeHight" data-start-value-from="@(Model.ComplexityMediumTo.TotalMinutes+1)" data-start-value-to="@Model.ComplexityHightTo.TotalMinutes"></div>
                @Html.ValidationMessageFor(model => model.ComplexityHightTo)
            </div>
        </div>
       
        <div class="buttonbar">
            <input type="submit" value="@ResourceScr.save" class="btn btn-default fullsize"/>
        </div>
    </div>
}
@using (Html.BeginForm("ToDefault", "UserSetting", FormMethod.Post))
{
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.UserId)
    @Html.HiddenFor(model => model.WorkingTime)
    @Html.HiddenFor(model => model.ParallelismPercentage)
    @Html.HiddenFor(model => model.ComplexityLowTo)
    @Html.HiddenFor(model => model.ComplexityMediumTo)
    @Html.HiddenFor(model => model.ComplexityHightTo)
    @Html.HiddenFor(model => model.ComplexityLowFrom)
    <input type="submit" value="@ResourceScr.ToDefault" class="btn btn-default fullsize" />
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}