LifeManagement/Controllers/AlertsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using LifeManagement.Attributes;
using LifeManagement.Extensions;
using LifeManagement.Models;
using LifeManagement.ViewModels;
using Microsoft.AspNet.Identity;

namespace LifeManagement.Controllers
{
    [System.Web.Mvc.Authorize]
    [Localize]
    public class AlertsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Alerts
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
            var alerts = db.Alerts.Where(x => x.UserId == userId && x.Date <= DateTime.UtcNow).ToList()
                .Select(x => new AlertViewModel{ Id = x.Id, Name = x.Name, Date = request.GetUserLocalTimeFromUtc(x.Date).ToString()});

            return View(alerts.ToList());
        }

        // GET: Alerts/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
           //return View(alert);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var alert = await db.Alerts.FindAsync(id);
            if (alert == null)
            {
                return HttpNotFound();
            }
            db.Alerts.Remove(alert);
            await db.SaveChangesAsync();
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }

        // POST: Alerts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            var alert = await db.Alerts.FindAsync(id);
            db.Alerts.Remove(alert);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LifeManagement/Controllers/TagsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using LifeManagement.Attributes;
using LifeManagement.Extensions;
using LifeManagement.Models;
using LifeManagement.Models.DB;
using Microsoft.AspNet.Identity;

namespace LifeManagement.Controllers
{
    [Authorize]
    [Localize]
    public class TagsController : ControllerExtensions
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Tags
        public async Task<ActionResult> Index()
        {
            var userId = User.Identity.GetUserId();
            var tags = db.Tags.Where(x => x.UserId == userId);
            return View(await tags.ToListAsync());
        }

        public async Task<ActionResult> GetRecords(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = await db.Tags.FindAsync(id);
            if (tag == null)
            {
                return RedirectToAction("Index", "Cabinet");
            }
            
            return View(tag);
        }

        // GET: Tags/Create
        public ActionResult Create()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView("Create");
            }
            return RedirectToPrevious();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Name")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                tag.Id = Guid.NewGuid();
                tag.UserId = User.Identity.GetUserId();
                db.Tags.Add(tag);
                await db.SaveChangesAsync();
                return Json(new { success = true });  
            }

            return View(tag);
        }

        // GET: Tags/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tag = await db.Tags.FindAsync(id);
            if (tag == null)
            {
                return RedirectToAction("Index", "Cabinet");
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("Edit", tag);
            }
            return RedirectToPrevious();
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,UserId,Name")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                tag.UserId = User.Identity.GetUserId();
                db.Entry(tag).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return Json(new { success = true });
            }

            return PartialView("Edit", tag);
        }

        // GET: Tags/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var tag = await db.Tags.FindAsync(id);
            if (tag == null)
            {
                return HttpNotFound();
            }

            if (Request.IsAjaxRequest())
            {
                return PartialView("Delete", tag);
            }
            return RedirectToPrevious();
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            var tag = await db.Tags.FindAsync(id);
            db.Tags.Remove(tag);
            await db.SaveChangesAsync();
            return Json(new { success = true });   
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LifeManagement/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Hangfire;
using LifeManagement.Attributes;
using LifeManagement.Enums;
using LifeManagement.Hubs;
using LifeManagement.Models;
using LifeManagement.Extensions;
using LifeManagement.Logic;
using LifeManagement.Models.DB;
using LifeManagement.ViewModels;
using LifeManagement.Resources;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.SignalR;
using Task = LifeManagement.Models.DB.Task;

namespace LifeManagement.Controllers
{
    [System.Web.Mvc.Authorize]
    [Localize]
    public class TasksController : ControllerExtensions
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult FilterTasks(RecordFilter recordFilter)
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
            var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().Where(x => x.CompletedOn == null).ToList();
            records = FilterRecords(records, recordFilter);
            ConvertTasksToUserLocalTime(request, records);
            return PartialView("Index", records);
        }

        public ActionResult GetTasksCompleatedToday()
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
             var today = DateTime.UtcNow.Date;
             var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().Where(x => x.CompletedOn.HasValue && x.CompletedOn.Value.Year== today.Year && x.CompletedOn.Value.Month == today.Month && x.CompletedOn.Value.Day == today.Day).ToList();
            ConvertTasksToUserLocalTime(request, records);
            return PartialView("Index", records);
        }
        public ActionResult GetTasksCompleatedWeek()
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
            var week = DateTime.UtcNow.Date.AddDays(-7);
            var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().Where(x => x.CompletedOn.HasValue && x.CompletedOn.Value > week).ToList();
            ConvertTasksToUserLocalTime(request, records);
            return PartialView("Index", records);
        }
        public ActionResult GetTasksByProject(Guid projectId)
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
            var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().Where(x => x.CompletedOn == null && x.ProjectId == projectId).ToList();
            ConvertTasksToUserLocalTime(request, records);
            return PartialView("Index", records);
        }

        public ActionResult GetTasksByTag(Guid tagId)
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
            var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().Where(x => x.CompletedOn == null).Include(x => x.Tags).Where(x => x.Tags.Any(y => y.Id == tagId)).ToList();
            ConvertTasksToUserLocalTime(request, records);
            return PartialView("Index", records);
        }

        public ActionResult GetTasksByText(string text)
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
            var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().ToList().Where(x => x.Name.ToLower().Contains(text.ToLower()));
            ConvertTasksToUserLocalTime(request, records);
            return PartialView("Index", records);
        }

        [HttpPost]
        public async Task<ActionResult> UpdateCompleteLevel(string id, byte level)
        {
            Guid taskId;
            Guid.TryParse(id, out taskId);
            if (taskId == null)
            {
                return Json(new { success = -1, time = "" });
            }

            var task = await db.Records.Include(x => x.Tags).FirstOrDefaultAsync(x => x.Id == taskId) as Task;
            if (task == null)
            {
                return Json(new { success = -1, time = "" });
            }
            if(task.CompleteLevel == level){
                return Json(new { success = 0, time = "" });
            }
            int res = 1;
            if (level < 100 && task.CompleteLevel == 100)
            {
                task.CompletedOn = null;
                res = 3;
            }
            task.CompleteLevel = level;
            if (task.CompleteLevel == 100)
            {
                res = 2;
                task.CompletedOn = DateTime.UtcNow;
            }
            if (ModelState.IsValid)
            {
                db.Entry(task).State = EntityState.Modified;
                await db.SaveChangesAsync();
                var request = System.Web.HttpContext.Current.Request;
                ConvertTaskToUserLocalTime(request, task);
                return Json(new { success = res, time = task.ConvertTimeToNice(true)});
            }

            return Json(new { success = -1, time = ""});
        }
        // GET: Tasks
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
            var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().ToList();
            ConvertTasksToUserLocalTime(request, records);
            return PartialView(records);
        }

        public ActionResult NothingToDoTask()
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
            var today = DateTime.UtcNow.Date.AddMinutes(1439);
            var dueDate = today.AddDays(7);
            var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().Where(x => !x.CompletedOn.HasValue &&
                ((!x.StartDate.HasValue && !x.EndDate.HasValue) ||
                (x.EndDate != null && x.EndDate <= dueDate && x.EndDate > today && (x.StartDate == null || (x.StartDate != null && x.StartDate > today))))).OrderBy(x => !x.IsImportant).ToList();
            ConvertTasksToUserLocalTime(request, records);
            return PartialView(records);
        }

        [HttpPost]
        public ActionResult MakeTask(Guid[] TasksId)
        {
            if (TasksId == null)
            {
                return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
            }
            var today = DateTime.UtcNow.Date;
            foreach (var guid in TasksId)
            {
                var task = db.Records.Find(guid);
                if (task != null)
                {
                    task.StartDate = today;
                    db.Entry(task).State = EntityState.Modified;
                    db.SaveChanges();
                }

            }
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }

        public ActionResult GenerateList()
        {
            var settings = new TaskListSettingsViewModel();
            ViewBag.Date = DateTime.Now.Date.ToString("dd.MM.yyyy");
            ViewBag.Time = "00:05";
            ViewBag.Hours = 0;
            ViewBag.Minutes = 5;
            var userId = User.Identity.GetUserId();
            ViewBag.ProjectId = new SelectList(db.Projects.Where(x => x.UserId == userId), "Id", "Path");
            return PartialView(settings);
        }

        [HttpPost]
        public async Task<ActionResult> GenerateList([Bind(Include = "Date,TimeToFill,ProjectId")]TaskListSettingsViewModel listSetting)
        {
            var userId = User.Identity.GetUserId();
            ViewBag.Date = listSetting.Date.ToString("dd.MM.yyyy");
            ViewBag.Time = listSetting.TimeToFill.Hours + ":" + listSetting.TimeToFill.Minutes;
            ViewBag.Hours = listSetting.TimeToFill.Hours;
            ViewBag.Minutes = listSetting.TimeToFill.Minutes;
            ViewBag.ProjectId = new SelectList(db.Projects.Where(x => x.UserId == userId), "Id", "Path");
            if (listSetting.Date < DateTime.UtcNow.Date)
            {
                ModelState.AddModelError("Date", ResourceScr.itsPast);
                return PartialView("GenerateList", listSetting);
            }
            listSetting.UserId = userId;
            var version = new VersionsViewModel();
            try
            {
                var algorithm = new ToDoManager(listSetting);
                version = await algorithm.Generate();
            }
            catch (Exception exception)
            {
                ModelState.AddModelError("Date", exception.Message);
                return PartialView("GenerateList", listSetting);
            }
            ViewData["idList"] = Guid.NewGuid();
            Session[ViewData["idList"].ToString()] = version;
            ViewData["Date"] = listSetting.Date;
            return PartialView("ChooseVariant", version);
        }

        [HttpPost]
        public async Task<ActionResult> ChooseVariant(DateTime date, Guid id)
        {
            try
            {
                VersionsViewModel version = (VersionsViewModel) Session[id.ToString()];
                var index = int.Parse(Request["radio"]);

                foreach (var task in version.ToDoLists[index].TasksTodo)
                {
                    task.StartDate = date;
                    var taskTmp = await db.Records.FindAsync(task.Id);
                    taskTmp.StartDate = date;
                }
                await db.SaveChangesAsync();
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return Json(new { success = true });
        }

LifeManagement/Views/Cabinet/AllEvents.cshtml
@{
    ViewBag.Title = ResourceScr.AllEvents;
}
@using LifeManagement.Enums
@using LifeManagement.Resources


<div id="linkblock">
    @{Html.RenderAction("Sidebar", "Cabinet");}
</div>
<div id="maincontent">
    @{Html.RenderAction("Index", "Alerts");}
    <div class="title">
        <h2 id="maintitle">@ResourceScr.AllEvents</h2>
      @Html.Partial("_QuickCreateIcon")
    </div>

    <div id="Today">
        <div class="subtitle"><h3>@ResourceScr.Today</h3></div>
        <div id="TodayEvent">
            @{Html.RenderAction("FilterEvents", "Events", new RouteValueDictionary { { "recordFilter", RecordFilter.Today } });}
        </div>
    </div>
    <div id="Future">
        <div class="subtitle"><h3>@ResourceScr.Future</h3></div>
        <div id="FutureEvent">
            @{Html.RenderAction("FilterEvents", "Events", new RouteValueDictionary { { "recordFilter", RecordFilter.Future } });}
        </div>
    </div>
</div>

LifeManagement/Views/Cabinet/AllTasks.cshtml
@{
    ViewBag.Title = ResourceScr.AllTask;
}
@using LifeManagement.Enums
@using LifeManagement.Resources


<div id="linkblock">
    @{Html.RenderAction("Sidebar", "Cabinet");}
</div>
<div id="maincontent">
    @{Html.RenderAction("Index", "Alerts");}
    <div class="title">
        <h2 id="maintitle">@ResourceScr.AllTask</h2>
       @Html.Partial("_QuickCreateIcon")
    </div>

    <div id="Overdue">
        <div class="subtitle"><h3>@ResourceScr.Overdue</h3></div>
        @{Html.RenderAction("FilterTasks", "Tasks", new RouteValueDictionary { { "recordFilter", RecordFilter.Overdue } });}
    </div>
    <div id="Today">
        <div class="subtitle"><h3>@ResourceScr.Today</h3></div>
        <div id="TodayTask">
            @{Html.RenderAction("FilterTasks", "Tasks", new RouteValueDictionary { { "recordFilter", RecordFilter.Today } });}
        </div>
    </div>
    <div id="Future">
        <div class="subtitle"><h3>@ResourceScr.Future</h3></div>
        <div id="FutureTask">
            @{Html.RenderAction("FilterTasks", "Tasks", new RouteValueDictionary { { "recordFilter", RecordFilter.Future } });}
        </div>
    </div>
    <div id="NoDueDate">
        <div class="subtitle"><h3>@ResourceScr.NoDueDate</h3></div>
        @{Html.RenderAction("FilterTasks", "Tasks", new RouteValueDictionary { { "recordFilter", RecordFilter.NoDueDate } });}
    </div>
    <div id="Compleated">
        <div class="subtitle"><h3>@ResourceScr.CompletedOnWeek</h3></div>
        @{Html.RenderAction("GetTasksCompleatedWeek", "Tasks");}
    </div>
</div>

LifeManagement/Views/Cabinet/Index.cshtml
@{
    ViewBag.Title = ResourceScr.Focus;
}
@using LifeManagement.Enums
@using LifeManagement.Extensions
@using LifeManagement.Resources


<div id="linkblock">
    @{Html.RenderAction("Sidebar", "Cabinet");}
</div>
<div id="maincontent">
    @{Html.RenderAction("Index", "Alerts");}
    <div class="title">
        <h2 id="maintitle">@ResourceScr.Focus</h2>
        @Html.Partial("_QuickCreateIcon")
    </div>
    
    <div id="Overdue">
        <div class="subtitle"><h3>@ResourceScr.Overdue</h3></div>
        @{Html.RenderAction("FilterTasks", "Tasks", new RouteValueDictionary { { "recordFilter", RecordFilter.Overdue } });}
    </div>
    <div id="Today">
        <div class="subtitle"><h3>@ResourceScr.Today</h3></div>
        <div id="TodayEvent">
            @{Html.RenderAction("FilterEvents", "Events", new RouteValueDictionary { { "recordFilter", RecordFilter.Today } });}
        </div>
        <div id="TodayTask">
            @{Html.RenderAction("FilterTasks", "Tasks", new RouteValueDictionary { { "recordFilter", RecordFilter.Today } });}
            @{Html.RenderAction("GetTasksCompleatedToday", "Tasks");}
        </div>
    </div>
    <div id="Tomorrow">
        <div class="subtitle"><h3>@ResourceScr.Tomorrow</h3></div>
        <div id="TomorrowTask">
            @{Html.RenderAction("FilterTasks", "Tasks", new RouteValueDictionary { { "recordFilter", RecordFilter.Tomorrow } });}
        </div>
        <div id="TomorrowEvent">
            @{Html.RenderAction("FilterEvents", "Events", new RouteValueDictionary { { "recordFilter", RecordFilter.Tomorrow } });}
        </div>
    </div>
</div>

LifeManagement/Views/Cabinet/SearchResult.cshtml
@{
    ViewBag.Title = ResourceScr.cabinet;
}
@using LifeManagement.Resources


<div id="linkblock">
    @{Html.RenderAction("Sidebar", "Cabinet");}
</div>
<div id="maincontent">
    @{Html.RenderAction("Index", "Alerts");}
    <div class="title">
        <h2 id="maintitle">@Session["Text"]</h2>
        @Html.Partial("_QuickCreateIcon")
    </div>
    <div id="SearchResult">
        <div>
            @{ Html.RenderAction("GetTasksByText", "Tasks", new { text = Session["Text"] });}
        </div>
        <div>
            @{ Html.RenderAction("GetEventsByText", "Events", new { text = Session["Text"] });}
        </div>
    </div>
  </div>

    

LifeManagement/Views/Cabinet/ShowStatisticResult.cshtml
@{
    ViewBag.Title = ResourceScr.Statistics;
}
@using LifeManagement.Resources
<script>
    $(function () {
        $("#tabs").tabs();
    });
</script>

<div id="linkblock">
    @{Html.RenderAction("Sidebar", "Cabinet");}
</div>
<div id="maincontent">
    @{Html.RenderAction("Index", "Alerts");}
    <div class="title">
        <h2 id="maintitle">@ResourceScr.Statistics</h2>
        @Html.Partial("_QuickCreateIcon")
    </div>
    <div>
        <div id="tabs">
            <ul>
                <li><a href="#tabs-1">@ResourceScr.StatisticsTasksPerDay</a></li>
                <li><a href="#tabs-2">@ResourceScr.StatisticsSuccess</a></li>
            </ul>
            <div id="tabs-1">
                <div>
                    <img src="@Url.Action("StatisticsTasksPerDay")" />
                </div>
            </div>
            <div id="tabs-2">
                <div>
                    <img src="@Url.Action("StatisticsSuccess")" />
                </div>
            </div>
        </div>
    </div>
</div>

LifeManagement/Views/Cabinet/Sidebar.cshtml
@{
    Layout = null;
}

@using LifeManagement.Extensions
@using LifeManagement.Models.DB
@using LifeManagement.Resources
@model IEnumerable<Project>

<script type='text/javascript' src="@Url.Content("~/Scripts/tree.js")"></script>
<script>
    $(function () {
        $(".datepicker").datepicker({ dateFormat: 'dd.mm.yy' }, $.datepicker.setDefaults($.datepicker.regional[LocalizeCode])).val();
    });
</script>
<div>
    <div>
        <ul class="tree">
            <li>@Html.ActionLink(@ResourceScr.Focus, "Index", "Cabinet")</li>
            <li>@Html.ActionLink(@ResourceScr.AllTask, "AllTasks", "Cabinet")</li>
            <li>@Html.ActionLink(@ResourceScr.AllEvents, "AllEvents", "Cabinet")</li>  
            <li>
                @using (@Html.BeginForm("TimetableOnDate", "Cabinet", FormMethod.Post, htmlAttributes: new {@id = "dateForm" }))
                {
                    <input type="submit" value="@ResourceScr.onDate" class="invisibleInput" />
                    <input class="datepicker invisibleInput CalendarIcon" onchange="onDate()" value="@(Session["FocusDate"] ?? DateTime.Today.AddDays(1).ToString("dd.MM.yyyy"))" type="text" name="FocusDate" />
                }

            </li>          
            
            <li>
                <div id="chapter_img1" onclick="doMenu('1');" class="closeBlock">@ResourceScr.Projects</div>
                <ul id="chapter1" class="subtree">
                    @foreach (var item in Model)
                    {
                        <li class="subpunct">
                           
                            @Html.ActionLink(item.ToString(), "GetTasks", "Projects", new { id = item.Id }, null)
                            @Html.DialogFormLink(" ", "edit", Url.Action("Edit", "Projects", new { id = item.Id }), ResourceScr.Details, "linkblock", Url.Action("Sidebar", "Cabinet"), 700, ResourceScr.HelpEdit)
                        </li>
                    }
                    <li>
                        @Html.DialogFormLink(ResourceScr.addProject, "addBlock", Url.Action("Create", "Projects"), ResourceScr.newProject, "linkblock", Url.Action("Sidebar", "Cabinet"), 700)
                    </li>
                </ul>
            </li>
            <li>
                <div id="chapter_img2" onclick="doMenu('2');" class="closeBlock">@ResourceScr.Tags</div>
                <ul id="chapter2" class="subtree">
                    @{Html.RenderAction("TagsList", "Cabinet");}
                </ul>
            </li>
            <li>@Html.ActionLink(@ResourceScr.Statistics, "ShowStatisticResult", "Cabinet")</li>
        </ul>
    </div>
</div>

LifeManagement/Views/Cabinet/TagsList.cshtml
@{
    Layout = null;
}
@using LifeManagement.Extensions
@using LifeManagement.Resources
@model IEnumerable<LifeManagement.Models.DB.Tag>


@foreach (var item in Model) {
    <li class="subpunct">
        @Html.ActionLink(item.Name, "GetRecords", "Tags", new { id = item.Id }, null) 
        @Html.DialogFormLink(" ", "edit", Url.Action("Edit", "Tags", new { id = item.Id }), ResourceScr.Details, "chapter2", Url.Action("TagsList", "Cabinet"), 500, ResourceScr.HelpEdit)
    </li>
}
<li>
    @Html.DialogFormLink(ResourceScr.addTag, "addBlock", Url.Action("Create", "Tags"), ResourceScr.newTag, "chapter2", Url.Action("TagsList", "Cabinet"), 700)
</li>

LifeManagement/Views/Cabinet/TimetableOnDate.cshtml
@model List<LifeManagement.Models.DB.Record>

@using LifeManagement.Extensions
@using LifeManagement.Models.DB
@using LifeManagement.Resources
@{
    ViewBag.Title = ResourceScr.onDate+" "+Session["FocusDate"];
}

<div id="linkblock">
    @{Html.RenderAction("Sidebar", "Cabinet");}
</div>
<div id="maincontent">
    @{Html.RenderAction("Index", "Alerts");}
    <div class="title">
        <h2 id="maintitle">@ResourceScr.onDate @Session["FocusDate"]</h2>
        @Html.Partial("_QuickCreateIcon")
    </div>
    @if (!Model.Any())
    {
          <h4 style="text-align: center;">@ResourceScr.NothingPlaning </h4>
    }
    @foreach (var item in Model)
{
    if (item is Task)
    {
        <div class="task @((item as Task).Complexity)">
            <div class="taskComleateLevel" data-id=@item.Id title="@ResourceScr.CompleteLevel">
                <input class="knob" data-width="45" data-height="45" data-angleoffset=-179 data-displayprevious=true data-anglearc=358 data-fgcolor="#0e0e0e" value='@((item as Task).CompleteLevel)'>
            </div>
            <div class="taskInfo">
                <div class="name">
                    @if (item.IsImportant)
                    {
                        <div class="Urgent"></div>
                    }
                    @item.Name
                </div>
                <div>
                    @Html.DialogFormLink(" ", "moreInfoIcon", Url.Action("Edit", "Tasks", new { id = item.Id }), ResourceScr.Details, "body-LifeManagment", HttpContext.Current.Request.Url.AbsoluteUri, 700)
                </div>
                <span class="time">@item.ConvertTimeToNice()</span>
                <div class="tags">
                    @foreach (var tag in item.Tags)
                    {
                        <text>@tag.Name </text>
                    }
                </div>
            </div>
        </div>
    }
    else
    {
            <div class="event">
                <div class="taskInfo">
                    <div class="name">
                        @if (item.IsImportant)
                        {
                            <div class="Urgent"></div>
                        }
                        @item.Name
                    </div>
                    <div>
                        @Html.DialogFormLink(" ", "moreInfoIcon", Url.Action("Edit", "Events", new { id = item.Id }), ResourceScr.Details, "body-LifeManagment", "", 700)
                    </div>
                    <span class="time">@item.ConvertTimeToNice()</span>
                    <div class="tags">
                        @foreach (var tag in item.Tags)
                        {
                            <text>@tag.Name </text>
                        }
                    </div>
                </div>
            </div>
        }
    }
</div>