LifeManagement/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using LifeManagement.Attributes;
using LifeManagement.Extensions;
using LifeManagement.Models;
using LifeManagement.Models.DB;
using Microsoft.AspNet.Identity;

namespace LifeManagement.Controllers
{
    [Authorize]
    [Localize]
    public class ProjectsController : ControllerExtensions
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Projects
        public async Task<ActionResult> Index()
        {
            var userId = User.Identity.GetUserId();
            var projects = db.Projects.Where(x => x.UserId == userId).Include(p => p.ParentProject);
            return View(await projects.ToListAsync());
        }

        public async Task<ActionResult> GetTasks(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = await db.Projects.FindAsync(id);
            if (project == null)
            {
                return RedirectToAction("Index", "Cabinet");
            }
            return View(project);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            var userId = User.Identity.GetUserId();
            ViewBag.ParentProjectId = new SelectList(db.Projects.Where(x => x.UserId == userId), "Id", "Path");
            if (Request.IsAjaxRequest())
            {
                return PartialView("Create");
            }
            return RedirectToPrevious();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ParentProjectId,Name")] Project project)
        {
            var userId = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                project.Id = Guid.NewGuid();
                project.UserId = userId;
                db.Projects.Add(project);
                await db.SaveChangesAsync();
               // return RedirectToPrevious();
                return Json(new { success = true });   
            }

            ViewBag.ParentProjectId = new SelectList(db.Projects.Where(x => x.Id != project.Id && x.UserId == userId), "Id", "Path", project.ParentProjectId);
            return PartialView("Create",project);
        }

        // GET: Projects/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var project = await db.Projects.FindAsync(id);
            if (project == null)
            {
                return RedirectToAction("Index", "Cabinet");
            }
            var parentListTmp = db.Projects.Where(x => x.UserId.Equals(project.UserId)).ToList();
            var parentList = parentListTmp.Where(project1 => project1.CanHasLikeSon(project.Id));
            ViewBag.ParentProjectId = new SelectList(parentList, "Id", "Path", project.ParentProjectId);
            if (Request.IsAjaxRequest())
            {
                return PartialView("Edit", project);
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,ParentProjectId,UserId,Name")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return Json(new { success = true });   
            }
            var parentListTmp = db.Projects.Where(x => x.UserId.Equals(project.UserId)).ToList();
            var parentList = parentListTmp.Where(project1 => project1.CanHasLikeSon(project.Id));
            ViewBag.ParentProjectId = new SelectList(parentList, "Id", "Path", project.ParentProjectId);
            return PartialView("Edit", project);
        }

        // GET: Projects/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var project = await db.Projects.FindAsync(id);
            if (project == null)
            {
                return RedirectToAction("Index", "Cabinet");
            }

            if (Request.IsAjaxRequest())
            {
                return PartialView("Delete", project);
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            var project = await db.Projects.FindAsync(id);
            db.Projects.RemoveRange(project.ChildProjects);
            db.Projects.Remove(project);
            await db.SaveChangesAsync();
            return Json(new { success = true });   
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LifeManagement/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Hangfire;
using LifeManagement.Attributes;
using LifeManagement.Enums;
using LifeManagement.Hubs;
using LifeManagement.Models;
using LifeManagement.Extensions;
using LifeManagement.Logic;
using LifeManagement.Models.DB;
using LifeManagement.ViewModels;
using LifeManagement.Resources;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.SignalR;
using Task = LifeManagement.Models.DB.Task;

namespace LifeManagement.Controllers
{
    [System.Web.Mvc.Authorize]
    [Localize]
    public class TasksController : ControllerExtensions
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult FilterTasks(RecordFilter recordFilter)
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
            var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().Where(x => x.CompletedOn == null).ToList();
            records = FilterRecords(records, recordFilter);
            ConvertTasksToUserLocalTime(request, records);
            return PartialView("Index", records);
        }

        public ActionResult GetTasksCompleatedToday()
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
             var today = DateTime.UtcNow.Date;
             var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().Where(x => x.CompletedOn.HasValue && x.CompletedOn.Value.Year== today.Year && x.CompletedOn.Value.Month == today.Month && x.CompletedOn.Value.Day == today.Day).ToList();
            ConvertTasksToUserLocalTime(request, records);
            return PartialView("Index", records);
        }
        public ActionResult GetTasksCompleatedWeek()
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
            var week = DateTime.UtcNow.Date.AddDays(-7);
            var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().Where(x => x.CompletedOn.HasValue && x.CompletedOn.Value > week).ToList();
            ConvertTasksToUserLocalTime(request, records);
            return PartialView("Index", records);
        }
        public ActionResult GetTasksByProject(Guid projectId)
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
            var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().Where(x => x.CompletedOn == null && x.ProjectId == projectId).ToList();
            ConvertTasksToUserLocalTime(request, records);
            return PartialView("Index", records);
        }

        public ActionResult GetTasksByTag(Guid tagId)
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
            var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().Where(x => x.CompletedOn == null).Include(x => x.Tags).Where(x => x.Tags.Any(y => y.Id == tagId)).ToList();
            ConvertTasksToUserLocalTime(request, records);
            return PartialView("Index", records);
        }

        public ActionResult GetTasksByText(string text)
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
            var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().ToList().Where(x => x.Name.ToLower().Contains(text.ToLower()));
            ConvertTasksToUserLocalTime(request, records);
            return PartialView("Index", records);
        }

        [HttpPost]
        public async Task<ActionResult> UpdateCompleteLevel(string id, byte level)
        {
            Guid taskId;
            Guid.TryParse(id, out taskId);
            if (taskId == null)
            {
                return Json(new { success = -1, time = "" });
            }

            var task = await db.Records.Include(x => x.Tags).FirstOrDefaultAsync(x => x.Id == taskId) as Task;
            if (task == null)
            {
                return Json(new { success = -1, time = "" });
            }
            if(task.CompleteLevel == level){
                return Json(new { success = 0, time = "" });
            }
            int res = 1;
            if (level < 100 && task.CompleteLevel == 100)
            {
                task.CompletedOn = null;
                res = 3;
            }
            task.CompleteLevel = level;
            if (task.CompleteLevel == 100)
            {
                res = 2;
                task.CompletedOn = DateTime.UtcNow;
            }
            if (ModelState.IsValid)
            {
                db.Entry(task).State = EntityState.Modified;
                await db.SaveChangesAsync();
                var request = System.Web.HttpContext.Current.Request;
                ConvertTaskToUserLocalTime(request, task);
                return Json(new { success = res, time = task.ConvertTimeToNice(true)});
            }

            return Json(new { success = -1, time = ""});
        }
        // GET: Tasks
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
            var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().ToList();
            ConvertTasksToUserLocalTime(request, records);
            return PartialView(records);
        }

        public ActionResult NothingToDoTask()
        {
            var userId = User.Identity.GetUserId();
            var request = System.Web.HttpContext.Current.Request;
            var today = DateTime.UtcNow.Date.AddMinutes(1439);
            var dueDate = today.AddDays(7);
            var records = db.Records.Where(x => x.UserId == userId).OfType<Task>().Where(x => !x.CompletedOn.HasValue &&
                ((!x.StartDate.HasValue && !x.EndDate.HasValue) ||
                (x.EndDate != null && x.EndDate <= dueDate && x.EndDate > today && (x.StartDate == null || (x.StartDate != null && x.StartDate > today))))).OrderBy(x => !x.IsImportant).ToList();
            ConvertTasksToUserLocalTime(request, records);
            return PartialView(records);
        }

        [HttpPost]
        public ActionResult MakeTask(Guid[] TasksId)
        {
            if (TasksId == null)
            {
                return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
            }
            var today = DateTime.UtcNow.Date;
            foreach (var guid in TasksId)
            {
                var task = db.Records.Find(guid);
                if (task != null)
                {
                    task.StartDate = today;
                    db.Entry(task).State = EntityState.Modified;
                    db.SaveChanges();
                }

            }
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }

        public ActionResult GenerateList()
        {
            var settings = new TaskListSettingsViewModel();
            ViewBag.Date = DateTime.Now.Date.ToString("dd.MM.yyyy");
            ViewBag.Time = "00:05";
            ViewBag.Hours = 0;
            ViewBag.Minutes = 5;
            var userId = User.Identity.GetUserId();
            ViewBag.ProjectId = new SelectList(db.Projects.Where(x => x.UserId == userId), "Id", "Path");
            return PartialView(settings);
        }

        [HttpPost]
        public async Task<ActionResult> GenerateList([Bind(Include = "Date,TimeToFill,ProjectId")]TaskListSettingsViewModel listSetting)
        {
            var userId = User.Identity.GetUserId();
            ViewBag.Date = listSetting.Date.ToString("dd.MM.yyyy");
            ViewBag.Time = listSetting.TimeToFill.Hours + ":" + listSetting.TimeToFill.Minutes;
            ViewBag.Hours = listSetting.TimeToFill.Hours;
            ViewBag.Minutes = listSetting.TimeToFill.Minutes;
            ViewBag.ProjectId = new SelectList(db.Projects.Where(x => x.UserId == userId), "Id", "Path");
            if (listSetting.Date < DateTime.UtcNow.Date)
            {
                ModelState.AddModelError("Date", ResourceScr.itsPast);
                return PartialView("GenerateList", listSetting);
            }
            listSetting.UserId = userId;
            var version = new VersionsViewModel();
            try
            {
                var algorithm = new ToDoManager(listSetting);
                version = await algorithm.Generate();
            }
            catch (Exception exception)
            {
                ModelState.AddModelError("Date", exception.Message);
                return PartialView("GenerateList", listSetting);
            }
            ViewData["idList"] = Guid.NewGuid();
            Session[ViewData["idList"].ToString()] = version;
            ViewData["Date"] = listSetting.Date;
            return PartialView("ChooseVariant", version);
        }

        [HttpPost]
        public async Task<ActionResult> ChooseVariant(DateTime date, Guid id)
        {
            try
            {
                VersionsViewModel version = (VersionsViewModel) Session[id.ToString()];
                var index = int.Parse(Request["radio"]);

                foreach (var task in version.ToDoLists[index].TasksTodo)
                {
                    task.StartDate = date;
                    var taskTmp = await db.Records.FindAsync(task.Id);
                    taskTmp.StartDate = date;
                }
                await db.SaveChangesAsync();
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return Json(new { success = true });
        }

LifeManagement/Views/Projects/Create.cshtml
@using System.Web.Mvc.Html5
@model LifeManagement.Models.DB.Project

@{
    ViewBag.Title = "Create";
}
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontalLM">

        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label LMсol-md" })
            @Html.Html5EditorFor(model => model.Name, htmlAttributes: new { @required = "true" })
                @Html.ValidationMessageFor(model => model.Name)
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ParentProjectId, htmlAttributes: new { @class = "control-label LMсol-md" })
                @Html.DropDownList("ParentProjectId", String.Empty)
                @Html.ValidationMessageFor(model => model.ParentProjectId)
        </div>
        
        <div class="buttonbar">
                <input type="submit" value="@LifeManagement.Resources.ResourceScr.Create" class="btn btn-default fullsize" />
        </div>
    </div>
}

LifeManagement/Views/Projects/Delete.cshtml
@model LifeManagement.Models.DB.Project

@{
    ViewBag.Title = "Delete";
}
<h3>@LifeManagement.Resources.ResourceScr.DeleteQustion @LifeManagement.Resources.ResourceScr.project "@Model.Name"?</h3>
<div>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="buttonbar">
            <input type="submit" value="@LifeManagement.Resources.ResourceScr.Delete" class="btn btn-default fullsize" />
        </div>
    }
</div>

LifeManagement/Views/Projects/Edit.cshtml
@using LifeManagement.Extensions
@using LifeManagement.Resources
@model LifeManagement.Models.DB.Project

@{
    ViewBag.Title = "Edit";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontalLM">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.UserId)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label LMсol-md" })
            <div>
                <div class="forma">@Html.EditorFor(model => model.Name)</div>
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ParentProjectId, htmlAttributes: new { @class = "control-label LMсol-md" })
            <div>
                <div class="forma">
                    @Html.DropDownList("ParentProjectId", String.Empty)
                </div>
                @Html.ValidationMessageFor(model => model.ParentProjectId)
            </div>
        </div>



        <div class="buttonbar">

            <input type="submit" value="@ResourceScr.save" class="btn btn-default halfsize" />
            @Html.DialogFormLink(ResourceScr.Delete, "btn btn-default halfsize", Url.Action("Delete", "Projects", new { id = Model.Id }), ResourceScr.Delete, "", "", 500)
                @*@Html.ActionLink(ResourceScr.Delete, "Delete", new { id = Model.Id }, new
                {
                    @class = "btn btn-default halfsize openDialog",
                    data_dialog_id = "23",
                    data_dialog_title = ResourceScr.Delete,
                    data_dialog_width = "500",
                    data_dialog_height = "auto"
                })*@

        </div>
    </div>
}

LifeManagement/Views/Projects/GetTasks.cshtml
@model LifeManagement.Models.DB.Project
@{
    ViewBag.Title = Model.Name;
}
@using LifeManagement.Resources


<div id="linkblock">
    @{Html.RenderAction("Sidebar", "Cabinet");}
</div>
<div id="maincontent">
    @{Html.RenderAction("Index", "Alerts");}
    <div class="title">
        <h2 id="maintitle">@ResourceScr.project @Model.Name </h2>
        @Html.Partial("_QuickCreateIcon")
    </div>

    <div id="TasksByProject">
            @{ Html.RenderAction("GetTasksByProject", "Tasks", new { projectId = Model.Id});}
    </div>
</div>

LifeManagement/Views/Projects/Index.cshtml
@model IEnumerable<LifeManagement.Models.DB.Project>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ParentProjectId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ParentProject.Path)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>